# build stage
FROM node:18-alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD [ "npm", "start" ]


# RUN npm run build

# # prod stage
# FROM node:18-alpine

# WORKDIR /usr/src/app

# ARG NODE_ENV=production
# ENV NODE_ENV=${NODE_ENV}

# COPY --from=build /usr/src/app/dist ./dist

# COPY package*.json ./

# RUN npm install --only=production

# RUN rm package*.json


# https://www.youtube.com/watch?v=mqI5ZcV3prI  참고 영상
