# fly.toml app configuration file generated for minari-client-prod on 2023-07-14T21:35:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minari-client-prod"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
