# fly.toml app configuration file generated for minari-client-stage on 2023-08-17T13:32:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "minari-client-stage"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
